#!/bin/bash

function fun {
    echo "this is an example of a func"
}

count=1
while [ $count -le 5 ]
do
    fun
    count=$[count+1]
done
echo "this is the end of loop"
fun
echo "this is the end of script"
