#!/bin/bash

function fun {
    temp=$[ $value + 5 ]
    result=$[ $temp *2 ]
}


temp=4
value=6

fun
echo "the result is $result"
if [ $temp -gt $value ]
then
    echo "temp is bigger"
else
    echo "temp is smaller"
fi
