#!/bin/bash

function arr4 {
    local originarr=(`echo "$@"`)
    local newarr=(`echo "$@"`)
    local elements=$#
    local i=0
    for(( i=0; i<elements; i++ )){
        newarr[$i]=$[ ${originarr[$i]} *2 ] 
    }
    echo ${newarr[*]}
}

myarr=(1 2 3 4 5)
echo "the origin arr is : ${myarr[*]}"
arg1=`echo ${myarr[*]}`
result=(`arr4 $arg1`)
echo "the new arr is ${result[*]}"
