#!/bin/bash

source ./66_func_lib

value1=10
value2=5

result1=`add $value1 $value2 `
result2=`mult $value1 $value2 `
result3=`div $value1 $value2 `

echo " result1=$result1 result2=$result2 result3=$result3 "
