/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flysnow_app_example131_hello */

#ifndef _Included_org_flysnow_app_example131_hello
#define _Included_org_flysnow_app_example131_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_flysnow_app_example131_hello
 * Method:    get_hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_flysnow_app_example131_hello_get_1hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
